FROM ubuntu:22.04
ENV TARGETARCH="linux-x64"
# Also can be "linux-arm", "linux-arm64".

RUN apt update && \
  apt upgrade -y && \
  apt install -y curl git jq libicu70 wget lsb-release kmod uidmap iptables fuse-overlayfs

# Install Azure CLI
RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash


WORKDIR /azp/

COPY ./start.sh ./
RUN chmod +x ./start.sh

# Create agent user and set up home directory
RUN useradd -m -d /home/agent agent
RUN chown -R agent:agent /azp /home/agent

# Configure environment variables for Docker rootless mode

USER agent
RUN curl -fsSL https://get.docker.com/rootless | sh && \
  $HOME/bin/dockerd-rootless-setuptool.sh install --force && bash <(curl -fsSL https://moonrepo.dev/install/moon.sh)

ENV PATH="$HOME/.moon/bin:$PATH"
RUN echo 'export PATH=/home/agent/.docker/bin:$PATH' >> /etc/bash.bashrc && \
  echo 'export DOCKER_HOST=unix:///run/user/1000/docker.sock' >> /etc/bash.bashrc
# Another option is to run the agent as root.
# ENV AGENT_ALLOW_RUNASROOT="true"

ENTRYPOINT [ "./start.sh" ]
